/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: '.'}],
  'version-3.32-sidebar': [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;