openapi: 3.0.0
info:
  title: senhasegura API Reference OAuth 2.0
  description: API endpoints from the senhasegura API Reference OAuth 2.0 Postman collection
  version: 1.0.0
servers:
- url: '{{senhasegura_url}}'
  description: Senhasegura Server
paths:
  /iso/pam/device:
    get:
      summary: List All Devices
      operationId: ListAllDevices
      parameters: []
      responses:
        '200':
          description: Successful response
    post:
      summary: Create/Update Device
      operationId: Create/UpdateDevice
      parameters:
      - name: hostname
        in: query
        required: true
        schema:
          type: string
        description: '[Obrigatório] Hostname do dispositivo.'
      - name: ip
        in: query
        required: true
        schema:
          type: string
        description: '[Obrigatório] IP do dispositivo.'
      - name: type
        in: query
        required: true
        schema:
          type: string
        description: '[Obrigatório] Tipo do dispositivo. Deve ser um tipo já cadastrado no senhasegura.'
      - name: vendor
        in: query
        required: true
        schema:
          type: string
        description: '[Obrigatório] Fabricante do dispositivo. Será criado caso não exista no senhasegura'
      - name: model
        in: query
        required: true
        schema:
          type: string
        description: '[Obrigatório] Modelo do dispositivo. Será criado caso não exista no senhasegura'
      - name: site
        in: query
        required: true
        schema:
          type: string
        description: '[Obrigatório] Localidade do dispositivo. Será criado caso não exista no senhasegura.'
      - name: device_domain
        in: query
        required: true
        schema:
          type: string
        description: '[Opcional] Domínio do dispositivo. Só são aceitos domínios previamente cadastrados.'
      - name: device_tags
        in: query
        required: true
        schema:
          type: string
        description: '[Opcional] Tags do dispositivo.'
      - name: connectivities
        in: query
        required: true
        schema:
          type: string
        description: '[Opcional] Conectividades do dispositivo.'
      - name: session_remote_conf
        in: query
        required: false
        schema:
          type: string
        description: '[Opcional] Expressão de login.'
      responses:
        '200':
          description: Successful response
  /iso/pam/device/{{device_id}}:
    get:
      summary: Access Device by ID
      operationId: AccessDevicebyID
      parameters: []
      responses:
        '200':
          description: Successful response
    delete:
      summary: Delete Device by ID
      operationId: DeleteDevicebyID
      parameters: []
      responses:
        '200':
          description: Successful response
    put:
      summary: Activate Device by ID
      operationId: ActivateDevicebyID
      parameters: []
      responses:
        '200':
          description: Successful response
  /iso/pam/credential/:
    get:
      summary: List All Credentials
      operationId: ListAllCredentials
      parameters: []
      responses:
        '200':
          description: Successful response
  /iso/pam/credential/user/pamusr:
    get:
      summary: List User Credentials
      operationId: ListUserCredentials
      parameters: []
      responses:
        '200':
          description: Successful response
  /iso/pam/credential/88:
    get:
      summary: Access Credential by ID
      operationId: AccessCredentialbyID
      parameters: []
      responses:
        '200':
          description: Successful response
  /iso/pam/credential:
    post:
      summary: Create/Update Credential
      operationId: Create/UpdateCredential
      parameters:
      - name: identifier
        in: query
        required: false
        schema:
          type: string
        description: Identificador único da credencial. Obrigatório somente para edição de credencial existente.
      - name: username
        in: query
        required: false
        schema:
          type: string
        description: '[Obrigatório] Username da credencial no senhasegura.'
      - name: additional
        in: query
        required: false
        schema:
          type: string
        description: '[Opcional] Informação adicional da credencial'
      - name: tags
        in: query
        required: false
        schema:
          type: string
        description: '[Opcional] Tags relacionadas a credencial'
      - name: credential_type
        in: query
        required: false
        schema:
          type: string
        description: '[Opcional] Tipo da credencial'
      - name: domain
        in: query
        required: false
        schema:
          type: string
        description: Domínio da credencial.
      - name: parent_password
        in: query
        required: false
        schema:
          type: string
        description: '[Opcional] ID da credencial pai'
      - name: hostname
        in: query
        required: false
        schema:
          type: string
        description: '[Obrigatório] Hostname do dispositivo ao qual a credencial está atribuída.'
      - name: ip
        in: query
        required: false
        schema:
          type: string
        description: '[Obrigatório] IP do dispositivo ao qual a credencial está atribuída.'
      - name: type
        in: query
        required: false
        schema:
          type: string
        description: '[Opcional] Somente para permitir a criação de um dispositivo junto da credencial'
      - name: vendor
        in: query
        required: false
        schema:
          type: string
        description: '[Opcional] Somente para permitir a criação de um dispositivo junto da credencial'
      - name: model
        in: query
        required: false
        schema:
          type: string
        description: '[Opcional] Somente para permitir a criação de um dispositivo junto da credencial'
      - name: site
        in: query
        required: false
        schema:
          type: string
        description: '[Opcional] Somente para permitir a criação de um dispositivo junto da credencial'
      - name: device_domain
        in: query
        required: false
        schema:
          type: string
        description: '[Opcional] Somente para permitir a criação de um dispositivo junto da credencial'
      - name: device_tags
        in: query
        required: false
        schema:
          type: string
        description: '[Opcional] Somente para permitir a criação de um dispositivo junto da credencial'
      - name: connectivities
        in: query
        required: false
        schema:
          type: string
        description: '[Opcional] Somente para permitir a criação de um dispositivo junto da credencial'
      - name: session_remote_conig
        in: query
        required: false
        schema:
          type: string
        description: '[Opcional] Somente para permitir a criação de um dispositivo junto da credencial'
      - name: content
        in: query
        required: false
        schema:
          type: string
        description: ''
      responses:
        '200':
          description: Successful response
  /iso/pam/credential/{{credential_id}}:
    delete:
      summary: Delete Credential by ID
      operationId: DeleteCredentialbyID
      parameters: []
      responses:
        '200':
          description: Successful response
  /iso/pam/key:
    post:
      summary: Criar chave SSH
      description: |
        Endpoint para criar uma nova chave SSH associada a dispositivos no senhasegura.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ip:
                  type: string
                  description: Endereço IP do dispositivo principal associado à chave SSH.
                  example: "10.66.33.15"
                hostname:
                  type: string
                  description: Nome do host do dispositivo principal associado à chave SSH.
                  example: "w2016"
                private_key:
                  type: string
                  description: |
                    Chave privada necessária para autenticação do usuário.
                    Exemplo: -----BEGIN OPENSSH PRIVATE KEY-----
                public_key:
                  type: string
                  description: Chave pública que permite que servidores verifiquem a identidade do usuário associado à chave privada correspondente.
                  example: ssh-ed25519 C1lZDI1NTE5AAawZxw...
                identifier:
                  type: string
                  description: |
                    String única definida pelo usuário ou pelo senhasegura para identificar a chave SSH.
                    Se deixado em branco, um identificador UUID será gerado automaticamente.
                  example: "sshkey3"
                username:
                  type: string
                  description: Nome de usuário relacionado à chave no dispositivo.
                  example: "dleite3"
                enabled:
                  type: boolean
                  description: Indica se a chave SSH está ativa ou inativa.
                  example: true
                devices:
                  type: array
                  items:
                    type: object
                    properties:
                      hostname:
                        type: string
                        description: Nome do host do dispositivo adicional.
                        example: "API device test"
                tags:
                  type: string
                  description: Palavras-chave associadas à chave SSH.
                  example: "mainsshkey"
                key_name:
                  type: string
                  description: Nome da chave SSH definido pelo usuário.
                  example: "teste4"
                password:
                  type: string
                  description: Senha opcional que fornece uma camada extra de segurança à chave privada.
                  example: "fkjwe87a5a8fa9a"
      responses:
        '201':
          description: Chave SSH criada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 201
                  response:
                    type: object
                    properties:
                      status:
                        type: integer
                        example: 201
                      message:
                        type: string
                        example: "Key successfully registered!"
                      error:
                        type: boolean
                        example: false
                      error_code:
                        type: integer
                        example: 0
                  key:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "92"
                      identifier:
                        type: string
                        example: "sshkey3"
                      devices:
                        type: array
                        items:
                          type: object
                          properties:
                            hostname:
                              type: string
                              example: "API device test"
                            ip:
                              type: string
                              example: "10.66.33.20"
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{{senhasegura_url}}/iso/oauth2/token/'
          scopes: {}
security:
  - oauth2: []