openapi: 3.0.0
info:
  title: Senhasegura API Reference OAuth 2.0
  description: API de Referência para OAuth 2.0 da plataforma Senhasegura, incluindo rotas para gerenciamento de dispositivos, credenciais, e outros módulos.
  version: 1.0.0

servers:
  - url: "{{senhasegura_url}}"

paths:
  /iso/pam/device:
    get:
      summary: List All Devices
      description: Endpoint para listar todos os dispositivos registrados no sistema.
      responses:
        '200':
          description: Lista de dispositivos recuperada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 0
                  response:
                    type: object
                    properties:
                      status:
                        type: integer
                        example: 0
                      message:
                        type: string
                      error:
                        type: boolean
                        example: true
                  devices:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "12345"
                        hostname:
                          type: string
                          example: "host123"
                        ip:
                          type: string
                          example: "hostname.example.com"
                        model:
                          type: string
                          example: "Windows Server"
                        type:
                          type: string
                          example: "Server"
                        vendor:
                          type: string
                          example: "Microsoft"

    post:
      summary: Create or Update Device
      description: Endpoint para criar ou atualizar um dispositivo.
      parameters:
        - name: hostname
          in: query
          required: true
          schema:
            type: string
            example: "sensui"
          description: Hostname do dispositivo.
        - name: ip
          in: query
          required: true
          schema:
            type: string
            example: "hostname.example.com"
          description: IP do dispositivo.
        - name: type
          in: query
          required: true
          schema:
            type: string
            example: "Server"
          description: Tipo do dispositivo.
      responses:
        '201':
          description: Dispositivo criado ou atualizado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Device created successfully."

  /iso/pam/device/{device_id}:
    get:
      summary: Access Device by ID
      description: Retorna informações de um dispositivo específico com base no ID fornecido.
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
          description: ID do dispositivo a ser acessado.
      responses:
        '200':
          description: Dispositivo encontrado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "12345"
                  hostname:
                    type: string
                    example: "host123"
                  ip:
                    type: string
                    example: "hostname.example.com"

    delete:
      summary: Delete Device by ID
      description: Endpoint para excluir um dispositivo com base no ID fornecido.
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
          description: ID do dispositivo a ser excluído.
      responses:
        '204':
          description: Dispositivo excluído com sucesso.

  /iso/pam/credential:
    get:
      summary: List All Credentials
      description: Endpoint para listar todas as credenciais registradas no sistema.
      responses:
        '200':
          description: Lista de credenciais recuperada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 0
                  credentials:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "cred123"
                        username:
                          type: string
                          example: "admin"
                        type:
                          type: string
                          example: "Local Administrator"

  /iso/pam/credential/{credential_id}:
    get:
      summary: Access Credential by ID
      description: Retorna informações de uma credencial específica com base no ID fornecido.
      parameters:
        - name: credential_id
          in: path
          required: true
          schema:
            type: string
          description: ID da credencial a ser acessada.
      responses:
        '200':
          description: Credencial encontrada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "cred123"
                  username:
                    type: string
                    example: "admin"
                  type:
                    type: string
                    example: "Local Administrator"

    delete:
      summary: Delete Credential by ID
      description: Endpoint para excluir uma credencial com base no ID fornecido.
      parameters:
        - name: credential_id
          in: path
          required: true
          schema:
            type: string
          description: ID da credencial a ser excluída.
      responses:
        '204':
          description: Credencial excluída com sucesso.

  /iso/session/remotesessions:
    get:
      summary: Get All Sessions Info
      description: Endpoint para listar todas as sessões remotas.
      responses:
        '200':
          description: Lista de sessões recuperada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessions:
                    type: array
                    items:
                      type: object
                      properties:
                        session_id:
                          type: string
                          example: "session123"
                        user:
                          type: string
                          example: "user1"
                        device:
                          type: string
                          example: "hostname.example.com"
                        protocol:
                          type: string
                          example: "ssh"

  /iso/session/remotesessions/{session_id}:
    get:
      summary: Get Session Info by ID
      description: Retorna informações de uma sessão específica com base no ID fornecido.
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
          description: ID da sessão a ser acessada.
      responses:
        '200':
          description: Sessão encontrada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_id:
                    type: string
                    example: "session123"
                  user:
                    type: string
                    example: "user1"
                  device:
                    type: string
                    example: "hostname.example.com"
                  protocol:
                    type: string
                    example: "ssh"

    delete:
      summary: Terminate Session by ID
      description: Endpoint para encerrar uma sessão com base no ID fornecido.
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
          description: ID da sessão a ser encerrada.
      responses:
        '204':
          description: Sessão encerrada com sucesso.